import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv("supply_chain_data.csv")
print(df.head())
print("\n Dataset shape:",df.shape)
print("\ncolumns:")
print(df.columns)
print("\nMissingvalues:")
print(df.isnull().sum())
revenue_by_product = df.groupby("Product type")["Revenue generated"].sum()
print("\nRevenue by product Type:")
print(revenue_by_product)
plt.figure(figsize=(8,5))
revenue_by_product.plot(kind="bar")
plt.title("Revenue by Product Type")
plt.ylabel("Revenue")
plt.show()
supplier_performance = df.groupby("Supplier name")["Defect rates"].mean()
plt.figure(figsize=(10,5))
supplier_performance.plot(kind="bar")
plt.title("Average Defect Rate by Supplier")
plt.ylabel("Defect Rate")
plt.show()
numeric_df = df.select_dtypes(include=['float64','int64'])
plt.figure(figsize=(12,8))
sns.heatmap(numeric_df.corr(),annot=True, cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show() 